import { Parent, Student, Subject, Chapter, LearningProgress } from '../types';

export const INITIAL_PARENT: Parent = {
  id: 'parent_athmik_001',
  name: 'Bishanth (Parent)',
  email: 'parent.athmik@example.com',
  phone: '+91 98470 00000',
  created_at: '2026-09-01T00:00:00.000Z',
  updated_at: '2026-09-01T00:00:00.000Z',
};

export const INITIAL_STUDENT: Student = {
  id: 'student_athmik_001',
  parent_id: 'parent_athmik_001',
  name: 'Athmik',
  class: '5',
  board: 'CBSE',
  academic_year: '2026-27',
  school_name: 'Amrutha Public School, Vatakara',
  date_of_birth: '2015-08-14',
  profile_photo_url: '',
  preferred_language: 'English',
  learning_preference: 'Visual + Explanation + Practice',
  created_at: '2026-09-01T00:00:00.000Z',
  updated_at: '2026-09-01T00:00:00.000Z',
};

export const INITIAL_SUBJECTS: Subject[] = [
  {
    id: 'sub_maths',
    name: 'Mathematics',
    description: 'Numbers, shapes, angles, fractions, and foundational mathematical logic.',
    class: '5',
    board: 'CBSE',
    icon: 'Calculator',
    active: true,
    display_order: 1,
    created_at: '2026-09-01T00:00:00.000Z',
    updated_at: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'sub_science',
    name: 'Science (EVS)',
    description: 'Living organisms, natural phenomena, environment, senses, and habitats.',
    class: '5',
    board: 'CBSE',
    icon: 'FlaskConical',
    active: true,
    display_order: 2,
    created_at: '2026-09-01T00:00:00.000Z',
    updated_at: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'sub_english',
    name: 'English',
    description: 'Literature, reading comprehension, grammar, vocabulary, and creative writing.',
    class: '5',
    board: 'CBSE',
    icon: 'BookOpen',
    active: true,
    display_order: 3,
    created_at: '2026-09-01T00:00:00.000Z',
    updated_at: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'sub_hindi',
    name: 'Hindi',
    description: 'Hindi prose, poetry, grammar (Vyakaran), and comprehension stories.',
    class: '5',
    board: 'CBSE',
    icon: 'Languages',
    active: true,
    display_order: 4,
    created_at: '2026-09-01T00:00:00.000Z',
    updated_at: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'sub_malayalam',
    name: 'Malayalam',
    description: 'Regional language literature, poems, Malayalam grammar, and cultural stories.',
    class: '5',
    board: 'CBSE',
    icon: 'GraduationCap',
    active: true,
    display_order: 5,
    created_at: '2026-09-01T00:00:00.000Z',
    updated_at: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'sub_social',
    name: 'Social Science',
    description: 'Our earth, geography, history, heritage, governance, and community life.',
    class: '5',
    board: 'CBSE',
    icon: 'Compass',
    active: true,
    display_order: 6,
    created_at: '2026-09-01T00:00:00.000Z',
    updated_at: '2026-09-01T00:00:00.000Z',
  },
];

export const INITIAL_CHAPTERS: Chapter[] = [
  // Mathematics sample chapters (Clearly marked sample CBSE curriculum)
  {
    id: 'chap_math_1',
    subject_id: 'sub_maths',
    chapter_number: 1,
    chapter_name: 'The Fish Tale',
    description: 'Sample CBSE Chapter: Large numbers, place value, fish market calculations, speed and distance.',
    active: true,
    display_order: 1,
    created_at: '2026-09-01T00:00:00.000Z',
    updated_at: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'chap_math_2',
    subject_id: 'sub_maths',
    chapter_number: 2,
    chapter_name: 'Shapes and Angles',
    description: 'Sample CBSE Chapter: Acute, obtuse, right angles, clock angles, and geometric shapes.',
    active: true,
    display_order: 2,
    created_at: '2026-09-01T00:00:00.000Z',
    updated_at: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'chap_math_3',
    subject_id: 'sub_maths',
    chapter_number: 3,
    chapter_name: 'How Many Squares?',
    description: 'Sample CBSE Chapter: Calculating area and perimeter using square grids and stamp puzzles.',
    active: true,
    display_order: 3,
    created_at: '2026-09-01T00:00:00.000Z',
    updated_at: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'chap_math_4',
    subject_id: 'sub_maths',
    chapter_number: 4,
    chapter_name: 'Parts and Wholes',
    description: 'Sample CBSE Chapter: Fractions, equal parts, chocolate division, and flag patterns.',
    active: true,
    display_order: 4,
    created_at: '2026-09-01T00:00:00.000Z',
    updated_at: '2026-09-01T00:00:00.000Z',
  },

  // Science sample chapters
  {
    id: 'chap_sci_1',
    subject_id: 'sub_science',
    chapter_number: 1,
    chapter_name: 'Super Senses',
    description: 'Sample CBSE Chapter: Amazing senses of sight, smell, hearing in ants, birds, and dogs.',
    active: true,
    display_order: 1,
    created_at: '2026-09-01T00:00:00.000Z',
    updated_at: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'chap_sci_2',
    subject_id: 'sub_science',
    chapter_number: 2,
    chapter_name: "A Snake Charmer's Story",
    description: 'Sample CBSE Chapter: Snakes, snake venom, instruments, and wildlife protection.',
    active: true,
    display_order: 2,
    created_at: '2026-09-01T00:00:00.000Z',
    updated_at: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'chap_sci_3',
    subject_id: 'sub_science',
    chapter_number: 3,
    chapter_name: 'From Tasting to Digesting',
    description: 'Sample CBSE Chapter: Tongue taste buds, digestion journey, glucose drip, and balanced diet.',
    active: true,
    display_order: 3,
    created_at: '2026-09-01T00:00:00.000Z',
    updated_at: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'chap_sci_4',
    subject_id: 'sub_science',
    chapter_number: 4,
    chapter_name: 'Mangoes Round the Year',
    description: 'Sample CBSE Chapter: Food spoilage, preservation, Mamidi Tandra (aam papad) preparation.',
    active: true,
    display_order: 4,
    created_at: '2026-09-01T00:00:00.000Z',
    updated_at: '2026-09-01T00:00:00.000Z',
  },

  // English sample chapters
  {
    id: 'chap_eng_1',
    subject_id: 'sub_english',
    chapter_number: 1,
    chapter_name: 'Ice-Cream Man',
    description: 'Sample CBSE Chapter: Summer poem, rhyme scheme, cold carts, joyful summer treats.',
    active: true,
    display_order: 1,
    created_at: '2026-09-01T00:00:00.000Z',
    updated_at: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'chap_eng_2',
    subject_id: 'sub_english',
    chapter_number: 2,
    chapter_name: 'Wonderful Waste!',
    description: 'Sample CBSE Chapter: Folktale of Travancore Maharaja and the invention of Avial from vegetable scraps.',
    active: true,
    display_order: 2,
    created_at: '2026-09-01T00:00:00.000Z',
    updated_at: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'chap_eng_3',
    subject_id: 'sub_english',
    chapter_number: 3,
    chapter_name: 'Teamwork',
    description: 'Sample CBSE Chapter: Collaborative spirit, passing the baton, together achieving dreams.',
    active: true,
    display_order: 3,
    created_at: '2026-09-01T00:00:00.000Z',
    updated_at: '2026-09-01T00:00:00.000Z',
  },

  // Hindi sample chapters
  {
    id: 'chap_hin_1',
    subject_id: 'sub_hindi',
    chapter_number: 1,
    chapter_name: 'Raakh Ki Rassi (राख की रस्सी)',
    description: 'Sample CBSE Chapter: Tibetan folktale about Lonpo Gar and his clever daughter-in-law.',
    active: true,
    display_order: 1,
    created_at: '2026-09-01T00:00:00.000Z',
    updated_at: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'chap_hin_2',
    subject_id: 'sub_hindi',
    chapter_number: 2,
    chapter_name: 'Faslon Ke Tyohar (फ़सलों के त्यौहार)',
    description: 'Sample CBSE Chapter: Harvest celebrations across India - Makar Sankranti, Pongal, Bihu, Sarhul.',
    active: true,
    display_order: 2,
    created_at: '2026-09-01T00:00:00.000Z',
    updated_at: '2026-09-01T00:00:00.000Z',
  },

  // Malayalam sample chapters
  {
    id: 'chap_mal_1',
    subject_id: 'sub_malayalam',
    chapter_number: 1,
    chapter_name: 'Nanmayude Pookkal (നന്മയുടെ പൂക്കൾ)',
    description: 'Sample CBSE Chapter: Moral values, respect, kindness and empathy through poetic prose.',
    active: true,
    display_order: 1,
    created_at: '2026-09-01T00:00:00.000Z',
    updated_at: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'chap_mal_2',
    subject_id: 'sub_malayalam',
    chapter_number: 2,
    chapter_name: 'Kuttikalam (കുട്ടിക്കാലം)',
    description: 'Sample CBSE Chapter: Childhood memories, village nature, play and learning in Kerala.',
    active: true,
    display_order: 2,
    created_at: '2026-09-01T00:00:00.000Z',
    updated_at: '2026-09-01T00:00:00.000Z',
  },

  // Social Science sample chapters
  {
    id: 'chap_soc_1',
    subject_id: 'sub_social',
    chapter_number: 1,
    chapter_name: 'Globe and Maps',
    description: 'Sample CBSE Chapter: Latitudes, longitudes, scales, directions, and reading physical symbols.',
    active: true,
    display_order: 1,
    created_at: '2026-09-01T00:00:00.000Z',
    updated_at: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'chap_soc_2',
    subject_id: 'sub_social',
    chapter_number: 2,
    chapter_name: 'The Northern Mountains',
    description: 'Sample CBSE Chapter: The Himalayas, Himadri, Himachal, Shivalik, climate and people.',
    active: true,
    display_order: 2,
    created_at: '2026-09-01T00:00:00.000Z',
    updated_at: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'chap_soc_3',
    subject_id: 'sub_social',
    chapter_number: 3,
    chapter_name: 'The Northern Plains',
    description: 'Sample CBSE Chapter: Ganga, Indus, Brahmaputra basins, fertile soil and agriculture.',
    active: true,
    display_order: 3,
    created_at: '2026-09-01T00:00:00.000Z',
    updated_at: '2026-09-01T00:00:00.000Z',
  },
];

// Initial progress starts completely empty so there is zero fake data.
// It populates as the student or parent marks chapters in progress or completed.
export const INITIAL_PROGRESS: LearningProgress[] = [];
